### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [cda-tum/dd_package#115]

**Comment by hillmich** [comment]
The project is header-only so apart from possibly copying files somewhere, there is not much to install. Do you have a specific usecase in mind?

**Comment by yurivict** [comment]
Headers only projects also install themselves. nlohmann-json is one example.

**Comment by hillmich** [comment]
Thanks for the input. Providing the means to install the library is not planned for the near term future. That being said, we‘d happily accept a pull request that provides this feature though.
