### ISSUE TITLE
weights being inadvertently modified in-place by follow, unfollow procedure

### ISSUE THREAD

**Issue by LieuweVinkhuijzen** [cda-tum/dd_package#84]
The weights of the DD seem to be inadvertently modified by the follow() and unfollow() procedure. But I'm not 100% confident that I understand that this is what the code does.

``        void unfollow(Edge<Node>& e, const short path, const LimEntry<> lim) {

                    if (path == 1) {
                        e.p->e[path].w.multiplyByMinusOne();
                    }
``  
Here the weight on the high edge is multiplied by -1. The weight on this edge is in the ComplexTable, so this modifies the weight of the edge. Is my understanding of this code right?

**Comment by burgholzer** [comment]
Is this still an issue or can this be closed?
